python
import re

def extract_info(source_code: str) -> dict:
    """
    Extracts the author and version information from a comment block in a source code file.

    Args:
        source_code (str): The content of a source code file.

    Returns:
        dict: A dictionary containing the extracted author and version information.
    """
    # Find the comment block in the source code
    comment_block = re.search(r'/\*(.|\n)*?\*/', source_code)
    if comment_block is None:
        return None

    # Extract the author and version information from the comment block
    author = re.search(r'@author\s+(\w+)', comment_block.group(0))
    version = re.search(r'@detail\s+Automatically generated by make_anlpy_project.sh (\d+\.\d+\.\d+)', comment_block.group(0))

    # Return the extracted information as a dictionary
    return {'author': author.group(1) if author else None, 'version': version.group(1) if version else None}
