python
import re

def extract_info(source_code: str) -> dict:
    pattern = r'/\*\*\s*@author\s+(.*?)\s+@detail\s+Automatically generated by\s+(\S+)\s+(\d+\.\d+\.\d+)\s+\*/'
    match = re.search(pattern, source_code, re.DOTALL)
    if match:
        author = match.group(1)
        tool = match.group(2)
        version = match.group(3)
        return {'author': author, 'version': version}
    else:
        return None
