import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class CurrencyResponse extends JSONResponse {

    @JsonProperty("Currency")
    private double currency;

    // Constructors, getters, and setters are automatically generated by Lombok
}