class CriterionArgs {
    // ...
    double calculateResidualNormReduction(double initialResidual) {
        // ...
        // Implement the specific criterion for the residual norm reduction calculation
        // ...
        return residualNormReduction;
    }
    // ...
};
